## Lab Assignment - 1, Part A
### Ayush Rawat
### E22CSEU0655

In [1]:
import numpy as np

In [2]:
# 1a : Check the version of NumPy and create 1D, 2D arrays.
print(np.__version__)

arr1a1 = np.array([1,2.0,3,4])
arr1a2 = np.array([[1,2,3],[4.0,5,6],[7,8,9]])

print(arr1a1)
print(arr1a2)

2.0.1
[1. 2. 3. 4.]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
# 1b : Check the data type and dimension of created arrays.
print("Data type of arr_1:",arr1a1.dtype)
print("Data type of arr_2:",arr1a2.dtype)

print("Dimension of arr1:",arr1a1.ndim)
print("Dimension of arr2:",arr1a2.ndim)

Data type of arr_1: float64
Data type of arr_2: float64
Dimension of arr1: 1
Dimension of arr2: 2


In [4]:
# 1c : Find the size of each element in the arrays.
# itemsize -> Returns the answer in bytes, for example if element is of int64 i.e 64 bits then the answer would be 64/8 = 8 bytes

print("Size of element in arr1:",arr1a1.itemsize)
print("Size of element in arr2:",arr1a2.itemsize)

Size of element in arr1: 8
Size of element in arr2: 8


In [5]:
# 1d : Find the number of rows and columns of 2D array.
(rows, cols) = arr1a2.shape
print("Rows:",rows)
print("Columns:",cols)

Rows: 3
Columns: 3


In [6]:
# 1e : An array of shape (2, 3) given, reshape the array into (3, 2).
arr1e = np.array([[1,2,3],[4,5,6]])
new_arr = arr1e.reshape(3,2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
# 2a : A 1D array is given as [4, 5, 6, 3, 9, 7]. Slice the array to get [6, 3, 9].
arr2a = np.array([4,5,6,3,9,7])
print(arr2a[2:5])

[6 3 9]


In [8]:
# 2b : A 2D array is given as [[1, 2, 3] [4, 5, 6]]. Slice the array to get [ [1, 2]].
arr2b = np.array([[1,2,3],[4,5,6]])
# print(arr2b[:1,:2])
print(arr2b[0][0:2])

[1 2]


In [9]:
# 3a : Concatenate two 1D arrays [4,5,6,7] and [3,4,1].
arr3a1 = np.array([4,5,6,7])
arr3a2 = np.array([3,4,1])

arr3a_new = np.concatenate((arr3a1, arr3a2))
print(arr3a_new)

[4 5 6 7 3 4 1]


In [10]:
# 3b : Perform concatenation of two 2D arrays in row-by-row manner.
arr3b1 = np.arange(9).reshape(3,3)
arr3b2 = np.arange(10,19).reshape(3,3)

arr3b_new = np.concatenate((arr3b1, arr3b2), axis = 1)
print(arr3b_new)

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


In [11]:
# 3c : Split the array [4, 5, 6, 3, 9,] into 3 sub-arrays.
arr3c = np.array([4,5,6,3,9])
arr3c_split = np.array_split(arr3c,3)
print(arr3c_split)

print(arr3c_split[0])
print(arr3c_split[1])
print(arr3c_split[2])

[array([4, 5]), array([6, 3]), array([9])]
[4 5]
[6 3]
[9]


In [12]:
# 3d : Split the array the 2D array [[ 1, 2, 3] [ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]] into 3 sub-arrays.
arr3d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
arr3d_split = np.array_split(arr3d, 3,axis = 0)
print(arr3d_split)

print(arr3d_split[0])
print(arr3d_split[1])
print(arr3d_split[2])

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[10 11 12]]


In [13]:
# 4a : Given an array [1, 2, 3, 4, 5, 4, 4]. Find the index of element 4. 
arr4a = np.array([1,2,3,4,5,4,4])
arr4a_res = np.where(arr4a == 4)
print(arr4a_res)

(array([3, 5, 6]),)


In [14]:
# 4b : Given a 2d array [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]]. Find the index of element 5.
arr4b = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[5, 11, 12]])
arr4b_res = np.where(arr4b == 5)
print(arr4b_res)

(array([1, 3]), array([1, 0]))


In [15]:
# 4c : Given an array [1, 2, 3, 4, 5, 6, 7, 8], find out the indices of odd elements and even elements.
arr4c = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr4c_even = np.where(arr4c % 2 == 0)
arr4c_odd = np.where(arr4c % 2 != 0)

print(arr4c_even)
print(arr4c_odd)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [16]:
# 5a :  Sort the elements of given 1D array [6, 5, 1, 2, 9, 10, 36, 7] in ascending and descending order
arr5a = np.array([6, 5, 1, 2, 9, 10, 36, 7])
print(np.sort(arr5a))

print(np.sort(arr5a)[::-1])


[ 1  2  5  6  7  9 10 36]
[36 10  9  7  6  5  2  1]


In [17]:
# 5b : Sort the elements of given 2D array [[5, 3, 7], [8, 10, 6], [40, -2, 7]] in ascending and descending order.
arr5b = np.array([[5, 3, 7], [8, 10, 6], [40, -2, 7]])

arr5b_asc_r = np.sort(arr5b, axis=0)
print("Ascending order (rows):\n", arr5b_asc_r)

arr5b_desc_r = np.sort(arr5b, axis=0)[::-1]
print("Descending order (rows):\n", arr5b_desc_r)

arr5b_asc_c = np.sort(arr5b, axis=1)
print("Ascending order (columns):\n", arr5b_asc_c)

arr5b_desc_c = np.sort(arr5b, axis=1)[::-1]
print("Descending order (columns):\n", arr5b_desc_c)

Ascending order (rows):
 [[ 5 -2  6]
 [ 8  3  7]
 [40 10  7]]
Descending order (rows):
 [[40 10  7]
 [ 8  3  7]
 [ 5 -2  6]]
Ascending order (columns):
 [[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]
Descending order (columns):
 [[-2  7 40]
 [ 6  8 10]
 [ 3  5  7]]


In [18]:
# 6a : Generate a 1-D array containing 6 random integers from 0 to 20.
arr6a = np.random.randint(-1,21,(6,))
print(arr6a)

[14  2 15 17  3 10]


In [19]:
# 6b : Generate a 1-D array containing 5 random floats.
arr6b = np.random.rand(5)
arr6b_res = np.add((np.multiply(arr6b, 10)), 1)
print(arr6b_res)

[10.63614663  8.97895263  9.17026648  8.98685306  6.96849718]


In [20]:
# 6c : Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 50.
arr6c = np.random.randint(0, 51,(3, 5))
print(arr6c)

[[49 49 48 50 30]
 [35 42 32 33 14]
 [36  8  6 40 38]]


In [21]:
# 6d : Generate a 2-D array with 3 rows, each row containing 5 random numbers.
arr6d = np.random.random((3, 5))
print(arr6d)

[[0.20604221 0.92111533 0.19160951 0.07695851 0.2555991 ]
 [0.17451056 0.18563385 0.18859474 0.75291844 0.6771292 ]
 [0.49315712 0.6333415  0.1688121  0.82579265 0.64476796]]


In [22]:
# 6e : Given a 1-D array [6, 5, 1, 2, 9, 10, 36, 7]. Shuffle the elements of the array randomly.
arr6d = np.array([6, 5, 1, 2, 9, 10, 36, 7])
np.random.shuffle(arr6d)
print(arr6d)

[ 6  1  7  2 36  9 10  5]


In [23]:
# 6f : Given a 2-D array [[ 1, 2, 3] [ 4, 5, 6][ 7, 8, 9] [10, 11, 12]]. Shuffle the elements of the array randomly.
arr6f = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.random.shuffle(arr6f)
print(arr6f)

# In this only rows are shuffling with each other, the elements of each row are in same order

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]
